template = ""
rev_id = 4
template_sha = "87be02986858c4b7ae5e8613b6f951c3c209b221"

[replacements]
__LICENSE__ = "CC-BY-4.0"
__UND2C_SRC__ = "lv"
__UND2C_TRG__ = "liv"
__UNDEFINED_SOURCE__ = "Latvian"
__UNDEFINED_TARGET__ = "Liv (Livonian)"
__UND_SRC__ = "lav"
__UND_TRG__ = "liv"
